---
- hosts: all
  become: yes  # Elevate privileges if necessary

  tasks:
    # Install Docker
    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Change ownership of docker.sock
      file:
        path: /var/run/docker.sock
        owner: root
        group: docker
        state: touch

    - name: Change docker.sock file permissions
      file:
        path: /var/run/docker.sock
        mode: "0666"

    - name: Restart Docker
      service:
        name: docker
        state: restarted

    - name: Pull the Docker image from DockerHub
      docker_image:
        name: a7medd3lii/systems-number
        tag: v1.1
        source: pull

    - name: Run Docker container
      docker_container:
        name: systems-number
        image: a7medd3lii/systems-number:v1.1
        state: started
        restart_policy: always
        ports:
          - "5000:5000"
